#!/usr/bin/env bash

##################################################################
# Polybar Pulseaudio Control                                     #
# https://github.com/marioortizmanero/polybar-pulseaudio-control #
##################################################################

# Script configuration (more info in the README)
OSD="no"  # On Screen Display message for KDE if enabled
INC=2  # Increment when lowering/rising the volume
MAX_VOL=150  # Maximum volume
AUTOSYNC="no"  # All programs have the same volume if enabled

MUTED_ICON=" "  # Muted volume icon
MUTED_COLOR="%{F#6b6b6b}"  # Color when the audio is muted

NOTIFICATIONS="no"  # Notifications when switching sinks if enabled

SOURCE_ICON=" "  # Icon always shown to the left of the default sink names

# Blacklist of PulseAudio sink names when switching between them. To obtain
# the names of your active sinks, use `pactl list sinks short`.
SOURCE_BLACKLIST=(
    "alsa_output.usb-Logitech_G433_Gaming_Headset_000000000000-00.iec958-stereo.monitor"
    "alsa_output.pci-0000_00_1f.3.analog-stereo.monitor"
)

# Maps PulseAudio sink names to human-readable names
declare -A SOURCE_NICKNAMES
SOURCE_NICKNAMES["alsa_input.usb-Logitech_G433_Gaming_Headset_000000000000-00.mono-fallback"]="Logitech Headset"
SOURCE_NICKNAMES["alsa_input.usb-Microsoft_Microsoft___LifeCam_Cinema_TM_-02.mono-fallback"]="Webcam"


# Environment & global constants for the script
LANGUAGE=en_US  # Some calls depend on English outputs of pactl
END_COLOR="%{F-}"


# Saves the currently default sink into a variable named `curSource`. It will
# return an error code when pulseaudio isn't running.
function getCurSource() {
    if ! pulseaudio --check; then return 1; fi
    curSource=$(pacmd list-sources | awk '/\* index:/{print $3}')
}


# Saves the sink passed by parameter's volume into a variable named `curVol`.
function getCurVol() {
    curVol=$(pacmd list-sources | grep -A 15 'index: '"$1"'' | grep 'volume:' | grep -E -v 'base volume:' | awk -F : '{print $3; exit}' | grep -o -P '.{0,3}%' | sed 's/.$//' | tr -d ' ')
}


# Saves the name of the sink passed by parameter into a variable named
# `sinkName`.
function getSourceName() {
    sinkName=$(pactl list sources short | awk -v source="$1" '{ if ($1 == source) {print $2} }')
}


# Saves the name to be displayed for the sink passed by parameter into a
# variable called `nickname`.
# If a mapping for the sink name exists, that is used. Otherwise, the string
# "Sink #<index>" is used.
function getNickname() {
    getSourceName "$1"
    if [ -n "${SOURCE_NICKNAMES[$sinkName]}" ]; then
        nickname="${SOURCE_NICKNAMES[$sinkName]}"
    else
        nickname="Source #$1"
    fi
}


# Saves the status of the sink passed by parameter into a variable named
# `isMuted`.
function getIsMuted() {
    isMuted=$(pacmd list-sources | grep -A 15 "index: $1" | awk '/muted/ {print $2; exit}')
}


# Saves all the sink inputs of the sink passed by parameter into a string
# named `sinkInputs`.
function getSinkInputs() {
    sinkInputs=$(pacmd list-source-outputs | grep -B 4 "source: $1 " | awk '/index:/{print $2}')
}


function volUp() {
    # Obtaining the current volume from pacmd into $curVol.
    if ! getCurSource; then
        echo "PulseAudio not running"
        return 1
    fi
    getCurVol "$curSource"
    local maxLimit=$((MAX_VOL - INC))

    # Checking the volume upper bounds so that if MAX_VOL was 100% and the
    # increase percentage was 3%, a 99% volume would top at 100% instead
    # of 102%. If the volume is above the maximum limit, nothing is done.
    if [ "$curVol" -le "$MAX_VOL" ] && [ "$curVol" -ge "$maxLimit" ]; then
        pactl set-source-volume "$curSource" "$MAX_VOL%"
    elif [ "$curVol" -lt "$maxLimit" ]; then
        pactl set-source-volume "$curSource" "+$INC%"
    fi

    if [ $OSD = "yes" ]; then showOSD "$curSource"; fi
    if [ $AUTOSYNC = "yes" ]; then volSync; fi
}


function volDown() {
    # Pactl already handles the volume lower bounds so that negative values
    # are ignored.
    if ! getCurSource; then
        echo "PulseAudio not running"
        return 1
    fi
    pactl set-source-volume "$curSource" "-$INC%"

    if [ $OSD = "yes" ]; then showOSD "$curSource"; fi
    if [ $AUTOSYNC = "yes" ]; then volSync; fi
}


function volSync() {
    if ! getCurSource; then
        echo "PulseAudio not running"
        return 1
    fi
    getSinkInputs "$curSource"
    getCurVol "$curSource"

    # Every output found in the active sink has their volume set to the
    # current one. This will only be called if $AUTOSYNC is `yes`.
    for each in $sinkInputs; do
        pactl set-source-output-volume "$each" "$curVol%"
    done
}


function volMute() {
    # Switch to mute/unmute the volume with pactl.
    if ! getCurSource; then
        echo "PulseAudio not running"
        return 1
    fi
    if [ "$1" = "toggle" ]; then
        getIsMuted "$curSource"
        if [ "$isMuted" = "yes" ]; then
            pactl set-source-mute "$curSource" "no"
        else
            pactl set-source-mute "$curSource" "yes"
        fi
    elif [ "$1" = "mute" ]; then
        pactl set-source-mute "$curSource" "yes"
    elif [ "$1" = "unmute" ]; then
        pactl set-source-mute "$curSource" "no"
    fi

    if [ $OSD = "yes" ]; then showOSD "$curSource"; fi
}


function nextSource() {
    # The final sinks list, removing the blacklisted ones from the list of
    # currently available sinks.
    if ! getCurSource; then
        echo "PulseAudio not running"
        return 1
    fi

    # Obtaining a tuple of sink indexes after removing the blacklisted devices
    # with their name.
    sinks=()
    local i=0
    while read -r line; do
        index=$(echo "$line" | cut -f1)
        name=$(echo "$line" | cut -f2)

        # If it's in the blacklist, continue the main loop. Otherwise, add
        # it to the list.
        for sink in "${SOURCE_BLACKLIST[@]}"; do
            if [ "$sink" = "$name" ]; then
                continue 2
            fi
        done

        sinks[$i]="$index"
        i=$((i + 1))
    done < <(pactl list short sources)

    # If the resulting list is empty, nothing is done
    if [ ${#sinks[@]} -eq 0 ]; then return; fi

    # If the current sink is greater or equal than last one, pick the first
    # sink in the list. Otherwise just pick the next sink avaliable.
    local newSink
    if [ "$curSource" -ge "${sinks[-1]}" ]; then
        newSink=${sinks[0]}
    else
        for sink in "${sinks[@]}"; do
            if [ "$curSource" -lt "$sink" ]; then
                newSink=$sink
                break
            fi
        done
    fi

    # The new sink is set
    pacmd set-default-source "$newSink"

    # Move all audio threads to new sink
    local inputs=$(pactl list short source-outputs | cut -f 1)
    for i in $inputs; do
        pacmd move-source-output "$i" "$newSink" &>/dev/null
    done

    if [ $NOTIFICATIONS = "yes" ]; then
        getNickname "$newSink"
        
        if command -v dunstify &>/dev/null; then
            notify="dunstify --replace 201839192"
        else
            notify="notify-send"
        fi
        $notify "PulseAudio" "Changed output to $nickname" --icon=audio-headphones-symbolic &
    fi
}


# This function assumes that PulseAudio is already running. It only supports
# KDE OSDs for now. It will show a system message with the status of the
# sink passed by parameter, or the currently active one by default.
function showOSD() {
    if [ -z "$1" ]; then
        curSource="$1"
    else
        getCurSource
    fi
    getCurVol "$curSource"
    getIsMuted "$curSource"
    qdbus org.kde.kded /modules/kosd showVolume "$curVol" "$isMuted"
}


function listen() {
    local firstOutputRun=0

    # Listen for changes and immediately create new output for the bar.
    # This is faster than having the script on an interval.
    LANG=$LANGUAGE pactl subscribe 2>/dev/null | {
        while true; do
            {
                output;
                sleep 0.01;
            }
        done
    }
}


function output() {
    if ! getCurSource; then
        echo "PulseAudio not running"
        return 1
    fi
    
    getCurVol "$curSource"
    getIsMuted "$curSource"
    getNickname "$curSource"

    # Showing the formatted message
    if [ "$isMuted" = "yes" ]; then
        echo "${MUTED_COLOR}${SOURCE_ICON}${nickname} (${MUTED_ICON}${curVol}%)${END_COLOR}"
    else
        echo "${SOURCE_ICON}${nickname} (${curVol}%)"
    fi
}


function usage() {
    echo "Usage: $0 ACTION"
    echo ""
    echo "Actions:"
    echo "    help              display this help and exit"
    echo "    output            print the PulseAudio status once"
    echo "    listen            listen for changes in PulseAudio to automatically"
    echo "                      update this script's output"
    echo "    up, down          increase or decrease the default source's volume"
    echo "    mute, unmute      mute or unmute the default source's audio"
    echo "    togmute           switch between muted and unmuted"
    echo "    next-source       switch to the next available source"
    echo "    sync              synchronize all the output streams volume to"
    echo "                      the be the same as the current source's volume"
    echo ""
    echo "Author:"
    echo "    Mario O. M."
    echo "More info on GitHub:"
    echo "    https://github.com/marioortizmanero/polybar-pulseaudio-control"
}


case "$1" in
    up)
        volUp
        ;;
    down)
        volDown
        ;;
    togmute)
        volMute toggle
        ;;
    mute)
        volMute mute
        ;;
    unmute)
        volMute unmute
        ;;
    sync)
        volSync
        ;;
    listen)
        listen
        ;;
    next-source)
        nextSource
        ;;
    output)
        output
        ;;
    *)
        usage
        ;;
esac
